name: Cypress Tests

on:
  push:
    branches:
      - main
    paths:
      - 'test-cypress/**.js'
      - 'test-cypress/**.json'
      - 'test-cypress/**.yml'

jobs:
  cypress-project-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.1

      - name: Install dependencies
        run: npm install
        working-directory: ./test-cypress

      - name: Run Cypress tests
        run: npm run cypress:headless
        working-directory: ./test-cypress
